#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 101.200.190.34
    port: 6379
    password: 13824253328@pwq
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    url: jdbc:mysql://101.200.190.34:3306/nsms_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: nsms
    password: NSMS@all3
    driver-class-name: com.mysql.cj.jdbc.Driver

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888

#blade配置
blade:
  prop:
    upload-domain: http://localhost:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true
